// Generated Polyglot Data for 50 Languages
window.LANGUAGES_DATA = [
  {
    "id": "01-python",
    "name": "Python",
    "ext": "py",
    "category": "Mainstream & Systems",
    "compiler": "cpython-3.12.7",
    "year": "1991",
    "creator": "Guido van Rossum",
    "paradigm": "Multi-paradigm (Object-oriented, imperative, functional, procedural)",
    "install": "python.org or `winget install Python.Python.3.12` / `brew install python` / `apt install python3`",
    "run_cmd": "python hello_world.py",
    "hw_code": "# ==========================================\n# Program: Hello World in Python\n# ==========================================\n\n# Step 1: Define our main entry function.\ndef main():\n    # 'print()' sends text to the terminal and appends a newline.\n    print(\"Hello, World!\")\n\n# Step 2: Run main() if executed directly.\nif __name__ == \"__main__\":\n    main()\n",
    "ops_code": "# ==========================================\n# Program: Basic Operations in Python (+, -, *, /, //, %)\n# ==========================================\n\ndef main():\n    a = 20\n    b = 6\n\n    print(f\"a = {a}, b = {b}\")\n    print(f\"Addition (a + b)        : {a + b}\")\n    print(f\"Subtraction (a - b)     : {a - b}\")\n    print(f\"Multiplication (a * b)  : {a * b}\")\n    print(f\"Division (a / b)        : {a / b}\")       # Float division\n    print(f\"Integer Division (a // b): {a // b}\")     # Truncating integer division\n    print(f\"Modulo (a % b)          : {a % b}\")       # Remainder of division\n\nif __name__ == \"__main__\":\n    main()\n"
  },
  {
    "id": "02-javascript",
    "name": "JavaScript",
    "ext": "js",
    "category": "Mainstream & Systems",
    "compiler": "nodejs-20.17.0",
    "year": "1995",
    "creator": "Brendan Eich",
    "paradigm": "Multi-paradigm (Event-driven, functional, imperative)",
    "install": "nodejs.org or `winget install OpenJS.NodeJS` / `brew install node` / `apt install nodejs`",
    "run_cmd": "node hello_world.js",
    "hw_code": "// ==========================================\n// Program: Hello World in JavaScript (Node.js)\n// ==========================================\n\nfunction main() {\n    console.log(\"Hello, World!\");\n}\n\nmain();\n",
    "ops_code": "// ==========================================\n// Program: Basic Operations in JavaScript (+, -, *, /, %)\n// ==========================================\n\nfunction main() {\n    const a = 20;\n    const b = 6;\n\n    console.log(`a = ${a}, b = ${b}`);\n    console.log(`Addition (a + b)        : ${a + b}`);\n    console.log(`Subtraction (a - b)     : ${a - b}`);\n    console.log(`Multiplication (a * b)  : ${a * b}`);\n    console.log(`Division (a / b)        : ${a / b}`);\n    console.log(`Integer Division        : ${Math.floor(a / b)}`);\n    console.log(`Modulo (a % b)          : ${a % b}`);\n}\n\nmain();\n"
  },
  {
    "id": "03-typescript",
    "name": "TypeScript",
    "ext": "ts",
    "category": "Mainstream & Systems",
    "compiler": "typescript-5.6.2",
    "year": "2012",
    "creator": "Anders Hejlsberg (Microsoft)",
    "paradigm": "Multi-paradigm (Static typed superset of JavaScript)",
    "install": "`npm install -g typescript ts-node` or `npx ts-node`",
    "run_cmd": "npx ts-node hello_world.ts",
    "hw_code": "// ==========================================\n// Program: Hello World in TypeScript\n// ==========================================\n\nfunction greet(message: string): void {\n    console.log(message);\n}\n\ngreet(\"Hello, World!\");\n",
    "ops_code": "// ==========================================\n// Program: Basic Operations in TypeScript (+, -, *, /, %)\n// ==========================================\n\nfunction calculate(a: number, b: number): void {\n    console.log(`a = ${a}, b = ${b}`);\n    console.log(`Addition (a + b)        : ${a + b}`);\n    console.log(`Subtraction (a - b)     : ${a - b}`);\n    console.log(`Multiplication (a * b)  : ${a * b}`);\n    console.log(`Division (a / b)        : ${a / b}`);\n    console.log(`Integer Division        : ${Math.floor(a / b)}`);\n    console.log(`Modulo (a % b)          : ${a % b}`);\n}\n\ncalculate(20, 6);\n"
  },
  {
    "id": "04-c",
    "name": "C",
    "ext": "c",
    "category": "Mainstream & Systems",
    "compiler": "gcc-13.2.0-c",
    "year": "1972",
    "creator": "Dennis Ritchie (Bell Labs)",
    "paradigm": "Imperative, Procedural",
    "install": "GCC / Clang / MSVC",
    "run_cmd": "gcc hello_world.c -o hello_world && ./hello_world",
    "hw_code": "/*\n * ==========================================\n * Program: Hello World in C\n * ==========================================\n */\n#include <stdio.h>\n\nint main(void) {\n    printf(\"Hello, World!\\n\");\n    return 0;\n}\n",
    "ops_code": "/*\n * ==========================================\n * Program: Basic Operations in C (+, -, *, /, %)\n * ==========================================\n */\n#include <stdio.h>\n\nint main(void) {\n    int a = 20;\n    int b = 6;\n\n    printf(\"a = %d, b = %d\\n\", a, b);\n    printf(\"Addition (a + b)        : %d\\n\", a + b);\n    printf(\"Subtraction (a - b)     : %d\\n\", a - b);\n    printf(\"Multiplication (a * b)  : %d\\n\", a * b);\n    printf(\"Integer Division (a / b): %d\\n\", a / b);             // Integer division truncates\n    printf(\"Float Division (float)  : %f\\n\", (float)a / (float)b); // Type casting for float\n    printf(\"Modulo (a % b)          : %d\\n\", a % b);             // Remainder operator\n\n    return 0;\n}\n"
  },
  {
    "id": "05-cpp",
    "name": "C++",
    "ext": "cpp",
    "category": "Mainstream & Systems",
    "compiler": "gcc-13.2.0",
    "year": "1985",
    "creator": "Bjarne Stroustrup",
    "paradigm": "Multi-paradigm (OOP, generic, procedural, functional)",
    "install": "G++ / Clang++",
    "run_cmd": "g++ -std=c++17 hello_world.cpp -o hello_world && ./hello_world",
    "hw_code": "/*\n * ==========================================\n * Program: Hello World in C++\n * ==========================================\n */\n#include <iostream>\n\nint main() {\n    std::cout << \"Hello, World!\" << std::endl;\n    return 0;\n}\n",
    "ops_code": "/*\n * ==========================================\n * Program: Basic Operations in C++ (+, -, *, /, %)\n * ==========================================\n */\n#include <iostream>\n\nint main() {\n    int a = 20;\n    int b = 6;\n\n    std::cout << \"a = \" << a << \", b = \" << b << std::endl;\n    std::cout << \"Addition (a + b)        : \" << (a + b) << std::endl;\n    std::cout << \"Subtraction (a - b)     : \" << (a - b) << std::endl;\n    std::cout << \"Multiplication (a * b)  : \" << (a * b) << std::endl;\n    std::cout << \"Integer Division (a / b): \" << (a / b) << std::endl;\n    std::cout << \"Float Division (double) : \" << (static_cast<double>(a) / b) << std::endl;\n    std::cout << \"Modulo (a % b)          : \" << (a % b) << std::endl;\n\n    return 0;\n}\n"
  },
  {
    "id": "06-csharp",
    "name": "C#",
    "ext": "cs",
    "category": "Mainstream & Systems",
    "compiler": "dotnetcore-8.0.301",
    "year": "2000",
    "creator": "Anders Hejlsberg (Microsoft)",
    "paradigm": "Multi-paradigm (Object-oriented, component-oriented, functional)",
    "install": ".NET SDK",
    "run_cmd": "dotnet run (or csc hello_world.cs && ./hello_world.exe)",
    "hw_code": "// ==========================================\n// Program: Hello World in C# (.NET)\n// ==========================================\nusing System;\n\nnamespace HelloWorldApp\n{\n    class Program\n    {\n        static void Main(string[] args)\n        {\n            Console.WriteLine(\"Hello, World!\");\n        }\n    }\n}\n",
    "ops_code": "// ==========================================\n// Program: Basic Operations in C# (+, -, *, /, %)\n// ==========================================\nusing System;\n\nnamespace BasicOperationsApp\n{\n    class Program\n    {\n        static void Main(string[] args)\n        {\n            int a = 20;\n            int b = 6;\n\n            Console.WriteLine($\"a = {a}, b = {b}\");\n            Console.WriteLine($\"Addition (a + b)        : {a + b}\");\n            Console.WriteLine($\"Subtraction (a - b)     : {a - b}\");\n            Console.WriteLine($\"Multiplication (a * b)  : {a * b}\");\n            Console.WriteLine($\"Integer Division (a / b): {a / b}\");\n            Console.WriteLine($\"Float Division (double) : {(double)a / b}\");\n            Console.WriteLine($\"Modulo (a % b)          : {a % b}\");\n        }\n    }\n}\n"
  },
  {
    "id": "07-java",
    "name": "Java",
    "ext": "java",
    "category": "Mainstream & Systems",
    "compiler": "openjdk-21.0.2",
    "year": "1995",
    "creator": "James Gosling (Sun Microsystems)",
    "paradigm": "Multi-paradigm (Object-oriented, generic, concurrent)",
    "install": "OpenJDK / Oracle JDK",
    "run_cmd": "javac HelloWorld.java && java HelloWorld",
    "hw_code": "// ==========================================\n// Program: Hello World in Java\n// ==========================================\npublic class HelloWorld {\n    public static void main(String[] args) {\n        System.out.println(\"Hello, World!\");\n    }\n}\n",
    "ops_code": "// ==========================================\n// Program: Basic Operations in Java (+, -, *, /, %)\n// ==========================================\npublic class BasicOperations {\n    public static void main(String[] args) {\n        int a = 20;\n        int b = 6;\n\n        System.out.println(\"a = \" + a + \", b = \" + b);\n        System.out.println(\"Addition (a + b)        : \" + (a + b));\n        System.out.println(\"Subtraction (a - b)     : \" + (a - b));\n        System.out.println(\"Multiplication (a * b)  : \" + (a * b));\n        System.out.println(\"Integer Division (a / b): \" + (a / b));\n        System.out.println(\"Float Division (double) : \" + ((double) a / b));\n        System.out.println(\"Modulo (a % b)          : \" + (a % b));\n    }\n}\n"
  },
  {
    "id": "08-go",
    "name": "Go",
    "ext": "go",
    "category": "Mainstream & Systems",
    "compiler": "go-1.22.4",
    "year": "2009",
    "creator": "Robert Griesemer, Rob Pike, Ken Thompson (Google)",
    "paradigm": "Multi-paradigm (Concurrent, imperative, procedural)",
    "install": "go.dev",
    "run_cmd": "go run hello_world.go",
    "hw_code": "// ==========================================\n// Program: Hello World in Go (Golang)\n// ==========================================\npackage main\n\nimport \"fmt\"\n\nfunc main() {\n    fmt.Println(\"Hello, World!\")\n}\n",
    "ops_code": "// ==========================================\n// Program: Basic Operations in Go (+, -, *, /, %)\n// ==========================================\npackage main\n\nimport \"fmt\"\n\nfunc main() {\n    a := 20\n    b := 6\n\n    fmt.Printf(\"a = %d, b = %d\\n\", a, b)\n    fmt.Printf(\"Addition (a + b)        : %d\\n\", a + b)\n    fmt.Printf(\"Subtraction (a - b)     : %d\\n\", a - b)\n    fmt.Printf(\"Multiplication (a * b)  : %d\\n\", a * b)\n    fmt.Printf(\"Integer Division (a / b): %d\\n\", a / b)\n    fmt.Printf(\"Float Division (float64): %f\\n\", float64(a) / float64(b))\n    fmt.Printf(\"Modulo (a % b)          : %d\\n\", a % b)\n}\n"
  },
  {
    "id": "09-rust",
    "name": "Rust",
    "ext": "rs",
    "category": "Mainstream & Systems",
    "compiler": "rust-1.80.0",
    "year": "2015",
    "creator": "Graydon Hoare (Mozilla Research)",
    "paradigm": "Multi-paradigm (Concurrent, functional, imperative, generic)",
    "install": "rustup.rs",
    "run_cmd": "rustc hello_world.rs && ./hello_world",
    "hw_code": "// ==========================================\n// Program: Hello World in Rust\n// ==========================================\nfn main() {\n    println!(\"Hello, World!\");\n}\n",
    "ops_code": "// ==========================================\n// Program: Basic Operations in Rust (+, -, *, /, %)\n// ==========================================\nfn main() {\n    let a: i32 = 20;\n    let b: i32 = 6;\n\n    println!(\"a = {}, b = {}\", a, b);\n    println!(\"Addition (a + b)        : {}\", a + b);\n    println!(\"Subtraction (a - b)     : {}\", a - b);\n    println!(\"Multiplication (a * b)  : {}\", a * b);\n    println!(\"Integer Division (a / b): {}\", a / b);\n    println!(\"Float Division (f64)    : {}\", (a as f64) / (b as f64));\n    println!(\"Modulo (a % b)          : {}\", a % b);\n}\n"
  },
  {
    "id": "10-kotlin",
    "name": "Kotlin",
    "ext": "kt",
    "category": "Mainstream & Systems",
    "compiler": "openjdk-21.0.2",
    "year": "2011",
    "creator": "JetBrains",
    "paradigm": "Multi-paradigm (Functional, object-oriented)",
    "install": "JetBrains Kotlin",
    "run_cmd": "kotlinc hello_world.kt -include-runtime -d hello_world.jar && java -jar hello_world.jar",
    "hw_code": "// ==========================================\n// Program: Hello World in Kotlin\n// ==========================================\nfun main() {\n    println(\"Hello, World!\")\n}\n",
    "ops_code": "// ==========================================\n// Program: Basic Operations in Kotlin (+, -, *, /, %)\n// ==========================================\nfun main() {\n    val a = 20\n    val b = 6\n\n    println(\"a = $a, b = $b\")\n    println(\"Addition (a + b)        : ${a + b}\")\n    println(\"Subtraction (a - b)     : ${a - b}\")\n    println(\"Multiplication (a * b)  : ${a * b}\")\n    println(\"Integer Division (a / b): ${a / b}\")\n    println(\"Float Division (toDouble): ${a.toDouble() / b}\")\n    println(\"Modulo (a % b)          : ${a % b}\")\n}\n"
  },
  {
    "id": "11-swift",
    "name": "Swift",
    "ext": "swift",
    "category": "Mainstream & Systems",
    "compiler": "swift-5.10.1",
    "year": "2014",
    "creator": "Chris Lattner (Apple)",
    "paradigm": "Multi-paradigm (Protocol-oriented, object-oriented, functional)",
    "install": "Xcode / swift.org",
    "run_cmd": "swift hello_world.swift",
    "hw_code": "// ==========================================\n// Program: Hello World in Swift\n// ==========================================\nprint(\"Hello, World!\")\n",
    "ops_code": "// ==========================================\n// Program: Basic Operations in Swift (+, -, *, /, %)\n// ==========================================\nlet a = 20\nlet b = 6\n\nprint(\"a = \\(a), b = \\(b)\")\nprint(\"Addition (a + b)        : \\(a + b)\")\nprint(\"Subtraction (a - b)     : \\(a - b)\")\nprint(\"Multiplication (a * b)  : \\(a * b)\")\nprint(\"Integer Division (a / b): \\(a / b)\")\nprint(\"Float Division (Double) : \\(Double(a) / Double(b))\")\nprint(\"Modulo (a % b)          : \\(a % b)\")\n"
  },
  {
    "id": "12-php",
    "name": "PHP",
    "ext": "php",
    "category": "Mainstream & Systems",
    "compiler": "php-8.3.8",
    "year": "1995",
    "creator": "Rasmus Lerdorf",
    "paradigm": "Multi-paradigm (Imperative, OOP, procedural)",
    "install": "php.net",
    "run_cmd": "php hello_world.php",
    "hw_code": "<?php\n// ==========================================\n// Program: Hello World in PHP\n// ==========================================\necho \"Hello, World!\n\";\n?>\n",
    "ops_code": "<?php\n// ==========================================\n// Program: Basic Operations in PHP (+, -, *, /, %)\n// ==========================================\n$a = 20;\n$b = 6;\n\necho \"a = $a, b = $b\n\";\necho \"Addition (a + b)        : \" . ($a + $b) . \"\n\";\necho \"Subtraction (a - b)     : \" . ($a - $b) . \"\n\";\necho \"Multiplication (a * b)  : \" . ($a * $b) . \"\n\";\necho \"Division (a / b)        : \" . ($a / $b) . \"\n\";\necho \"Integer Division (intdiv): \" . intdiv($a, $b) . \"\n\";\necho \"Modulo (a % b)          : \" . ($a % $b) . \"\n\";\n?>\n"
  },
  {
    "id": "13-ruby",
    "name": "Ruby",
    "ext": "rb",
    "category": "Mainstream & Systems",
    "compiler": "ruby-3.3.4",
    "year": "1995",
    "creator": "Yukihiro Matsumoto (Matz)",
    "paradigm": "Multi-paradigm (Pure object-oriented, imperative, functional)",
    "install": "ruby-lang.org",
    "run_cmd": "ruby hello_world.rb",
    "hw_code": "# ==========================================\n# Program: Hello World in Ruby\n# ==========================================\nputs \"Hello, World!\"\n",
    "ops_code": "# ==========================================\n# Program: Basic Operations in Ruby (+, -, *, /, %)\n# ==========================================\na = 20\nb = 6\n\nputs \"a = #{a}, b = #{b}\"\nputs \"Addition (a + b)        : #{a + b}\"\nputs \"Subtraction (a - b)     : #{a - b}\"\nputs \"Multiplication (a * b)  : #{a * b}\"\nputs \"Integer Division (a / b): #{a / b}\"\nputs \"Float Division (to_f)   : #{a.to_f / b}\"\nputs \"Modulo (a % b)          : #{a % b}\"\n"
  },
  {
    "id": "14-r",
    "name": "R",
    "ext": "r",
    "category": "Scientific & Data",
    "compiler": "r-4.4.1",
    "year": "1993",
    "creator": "Ross Ihaka and Robert Gentleman",
    "paradigm": "Multi-paradigm (Functional, array, procedural)",
    "install": "r-project.org",
    "run_cmd": "Rscript hello_world.r",
    "hw_code": "# ==========================================\n# Program: Hello World in R\n# ==========================================\ncat(\"Hello, World!\n\")\n",
    "ops_code": "# ==========================================\n# Program: Basic Operations in R (+, -, *, /, %/%, %%)\n# ==========================================\na <- 20\nb <- 6\n\ncat(sprintf(\"a = %d, b = %d\n\", a, b))\ncat(sprintf(\"Addition (a + b)        : %d\n\", a + b))\ncat(sprintf(\"Subtraction (a - b)     : %d\n\", a - b))\ncat(sprintf(\"Multiplication (a * b)  : %d\n\", a * b))\ncat(sprintf(\"Division (a / b)        : %f\n\", a / b))\ncat(sprintf(\"Integer Division (a %%/%% b): %d\n\", a %/% b)) # %/% is integer division in R\ncat(sprintf(\"Modulo (a %%%% b)         : %d\n\", a %% b))   # %% is modulo in R\n"
  },
  {
    "id": "15-julia",
    "name": "Julia",
    "ext": "jl",
    "category": "Scientific & Data",
    "compiler": "julia-1.10.4",
    "year": "2012",
    "creator": "Jeff Bezanson et al.",
    "paradigm": "Multi-paradigm (Multiple dispatch, functional, procedural)",
    "install": "julialang.org",
    "run_cmd": "julia hello_world.jl",
    "hw_code": "# ==========================================\n# Program: Hello World in Julia\n# ==========================================\nprintln(\"Hello, World!\")\n",
    "ops_code": "# ==========================================\n# Program: Basic Operations in Julia (+, -, *, /, %, div)\n# ==========================================\na = 20\nb = 6\n\nprintln(\"a = $a, b = $b\")\nprintln(\"Addition (a + b)        : $(a + b)\")\nprintln(\"Subtraction (a - b)     : $(a - b)\")\nprintln(\"Multiplication (a * b)  : $(a * b)\")\nprintln(\"Division (a / b)        : $(a / b)\")\nprintln(\"Integer Division (div)  : $(div(a, b))\")\nprintln(\"Modulo (a % b)          : $(a % b)\")\n"
  },
  {
    "id": "16-matlab",
    "name": "MATLAB / GNU Octave",
    "ext": "m",
    "category": "Scientific & Data",
    "compiler": "octave-8.4.0",
    "year": "1984",
    "creator": "Cleve Moler (MathWorks)",
    "paradigm": "Array programming, procedural",
    "install": "MATLAB or GNU Octave",
    "run_cmd": "octave --silent hello_world.m",
    "hw_code": "% ==========================================\n% Program: Hello World in MATLAB / GNU Octave\n% ==========================================\ndisp('Hello, World!');\n",
    "ops_code": "% ==========================================\n% Program: Basic Operations in MATLAB / GNU Octave\n% ==========================================\na = 20;\nb = 6;\n\nfprintf('a = %d, b = %d\\n', a, b);\nfprintf('Addition (a + b)        : %d\\n', a + b);\nfprintf('Subtraction (a - b)     : %d\\n', a - b);\nfprintf('Multiplication (a * b)  : %d\\n', a * b);\nfprintf('Division (a / b)        : %f\\n', a / b);\nfprintf('Integer Division (idiv) : %d\\n', fix(a / b));\nfprintf('Modulo (mod(a, b))      : %d\\n', mod(a, b));\n"
  },
  {
    "id": "17-zig",
    "name": "Zig",
    "ext": "zig",
    "category": "Scientific & Data",
    "compiler": "zig-0.13.0",
    "year": "2016",
    "creator": "Andrew Kelley",
    "paradigm": "Imperative, Systems",
    "install": "ziglang.org",
    "run_cmd": "zig run hello_world.zig",
    "hw_code": "// ==========================================\n// Program: Hello World in Zig\n// ==========================================\nconst std = @import(\"std\");\n\npub fn main() !void {\n    const stdout = std.io.getStdOut().writer();\n    try stdout.print(\"Hello, World!\\n\", .{});\n}\n",
    "ops_code": "// ==========================================\n// Program: Basic Operations in Zig (+, -, *, @divTrunc, @rem)\n// ==========================================\nconst std = @import(\"std\");\n\npub fn main() !void {\n    const stdout = std.io.getStdOut().writer();\n    const a: i32 = 20;\n    const b: i32 = 6;\n\n    try stdout.print(\"a = {d}, b = {d}\\n\", .{a, b});\n    try stdout.print(\"Addition (a + b)        : {d}\\n\", .{a + b});\n    try stdout.print(\"Subtraction (a - b)     : {d}\\n\", .{a - b});\n    try stdout.print(\"Multiplication (a * b)  : {d}\\n\", .{a * b});\n    try stdout.print(\"Integer Division (div)  : {d}\\n\", .{@divTrunc(a, b)});\n    try stdout.print(\"Float Division          : {d}\\n\", .{@as(f64, @floatFromInt(a)) / @as(f64, @floatFromInt(b))});\n    try stdout.print(\"Modulo (@rem)           : {d}\\n\", .{@rem(a, b)});\n}\n"
  },
  {
    "id": "18-assembly",
    "name": "Assembly (x86_64 NASM)",
    "ext": "asm",
    "category": "Scientific & Data",
    "compiler": "gcc-13.2.0",
    "year": "1970s",
    "creator": "AMD / Intel",
    "paradigm": "Low-level Assembly",
    "install": "NASM & GCC/LD",
    "run_cmd": "nasm -f elf64 hello_world.asm -o hello_world.o && ld hello_world.o -o hello_world && ./hello_world",
    "hw_code": "; ==========================================\n; Program: Hello World in x86_64 Assembly (Linux NASM)\n; ==========================================\nsection .data\n    msg db \"Hello, World!\", 0x0a\n    len equ $ - msg\n\nsection .text\n    global _start\n\n_start:\n    mov rax, 1\n    mov rdi, 1\n    mov rsi, msg\n    mov rdx, len\n    syscall\n\n    mov rax, 60\n    xor rdi, rdi\n    syscall\n",
    "ops_code": "; ==========================================\n; Program: Basic Operations in x86_64 Assembly (NASM + printf)\n; Demonstrates CPU instructions: add, sub, imul, idiv\n; ==========================================\nsection .data\n    fmt db \"a = 20, b = 6\", 10\n        db \"Addition: %d, Subtraction: %d, Multiplication: %d, Division: %d, Modulo: %d\", 10, 0\n\nsection .text\n    global main\n    extern printf\n\nmain:\n    push rbp\n    mov rbp, rsp\n\n    ; a = 20, b = 6\n    ; 1. Addition (20 + 6 = 26)\n    mov r12, 20\n    add r12, 6          ; r12 = 26\n\n    ; 2. Subtraction (20 - 6 = 14)\n    mov r13, 20\n    sub r13, 6          ; r13 = 14\n\n    ; 3. Multiplication (20 * 6 = 120)\n    mov rax, 20\n    imul rax, 6         ; rax = 120\n    mov r14, rax\n\n    ; 4. Division & Modulo (20 / 6 -> quotient 3, remainder 2)\n    mov rax, 20\n    cqo                 ; Sign-extend rax into rdx:rax\n    mov rbx, 6\n    idiv rbx            ; rax = quotient (3), rdx = remainder (2)\n    mov r15, rax        ; r15 = 3 (division)\n    mov rbx, rdx        ; rbx = 2 (modulo)\n\n    ; Print results via printf(fmt, add, sub, mul, div, mod)\n    mov rdi, fmt\n    mov rsi, r12\n    mov rdx, r13\n    mov rcx, r14\n    mov r8, r15\n    mov r9, rbx\n    xor eax, eax\n    call printf\n\n    xor eax, eax\n    leave\n    ret\n"
  },
  {
    "id": "19-d",
    "name": "D",
    "ext": "d",
    "category": "Scientific & Data",
    "compiler": "dmd-2.108.1",
    "year": "2001",
    "creator": "Walter Bright (Digital Mars)",
    "paradigm": "Multi-paradigm (OOP, generic, functional, imperative)",
    "install": "dlang.org",
    "run_cmd": "dmd -run hello_world.d",
    "hw_code": "// ==========================================\n// Program: Hello World in D\n// ==========================================\nimport std.stdio;\n\nvoid main() {\n    writeln(\"Hello, World!\");\n}\n",
    "ops_code": "// ==========================================\n// Program: Basic Operations in D (+, -, *, /, %)\n// ==========================================\nimport std.stdio;\n\nvoid main() {\n    int a = 20;\n    int b = 6;\n\n    writefln(\"a = %d, b = %d\", a, b);\n    writefln(\"Addition (a + b)        : %d\", a + b);\n    writefln(\"Subtraction (a - b)     : %d\", a - b);\n    writefln(\"Multiplication (a * b)  : %d\", a * b);\n    writefln(\"Integer Division (a / b): %d\", a / b);\n    writefln(\"Float Division (double) : %f\", cast(double)a / b);\n    writefln(\"Modulo (a % b)          : %d\", a % b);\n}\n"
  },
  {
    "id": "20-nim",
    "name": "Nim",
    "ext": "nim",
    "category": "Scientific & Data",
    "compiler": "nim-2.0.4",
    "year": "2008",
    "creator": "Andreas Rumpf",
    "paradigm": "Multi-paradigm (Metaprogramming, functional, procedural)",
    "install": "nim-lang.org",
    "run_cmd": "nim compile --run hello_world.nim",
    "hw_code": "# ==========================================\n# Program: Hello World in Nim\n# ==========================================\necho \"Hello, World!\"\n",
    "ops_code": "# ==========================================\n# Program: Basic Operations in Nim (+, -, *, /, div, mod)\n# ==========================================\nlet a = 20\nlet b = 6\n\necho \"a = \", a, \", b = \", b\necho \"Addition (a + b)        : \", a + b\necho \"Subtraction (a - b)     : \", a - b\necho \"Multiplication (a * b)  : \", a * b\necho \"Float Division (a / b)  : \", a / b     # '/' returns a float\necho \"Integer Division (div)  : \", a div b   # 'div' is integer division\necho \"Modulo (mod)            : \", a mod b   # 'mod' is modulo\n"
  },
  {
    "id": "21-fortran",
    "name": "Fortran",
    "ext": "f90",
    "category": "Scientific & Data",
    "compiler": "gcc-13.2.0",
    "year": "1957",
    "creator": "John Backus (IBM)",
    "paradigm": "Array, imperative, procedural",
    "install": "GFortran",
    "run_cmd": "gfortran hello_world.f90 -o hello_world && ./hello_world",
    "hw_code": "! ==========================================\n! Program: Hello World in Modern Fortran (90+)\n! ==========================================\nprogram hello_world\n    implicit none\n    print *, \"Hello, World!\"\nend program hello_world\n",
    "ops_code": "! ==========================================\n! Program: Basic Operations in Modern Fortran (+, -, *, /, mod)\n! ==========================================\nprogram basic_operations\n    implicit none\n    integer :: a, b\n\n    a = 20\n    b = 6\n\n    print *, \"a = 20, b = 6\"\n    print *, \"Addition (a + b)        : \", a + b\n    print *, \"Subtraction (a - b)     : \", a - b\n    print *, \"Multiplication (a * b)  : \", a * b\n    print *, \"Integer Division (a / b): \", a / b\n    print *, \"Float Division (real)   : \", real(a) / real(b)\n    print *, \"Modulo (mod(a, b))      : \", mod(a, b)\nend program basic_operations\n"
  },
  {
    "id": "22-ada",
    "name": "Ada",
    "ext": "adb",
    "category": "Scientific & Data",
    "compiler": "gnat-13.2.0",
    "year": "1980",
    "creator": "Jean Ichbiah",
    "paradigm": "Multi-paradigm (Strongly typed, concurrent, OOP)",
    "install": "GNAT Ada Compiler",
    "run_cmd": "gnatmake hello_world.adb && ./hello_world",
    "hw_code": "-- ==========================================\n-- Program: Hello World in Ada\n-- ==========================================\nwith Ada.Text_IO; use Ada.Text_IO;\n\nprocedure Hello_World is\nbegin\n    Put_Line (\"Hello, World!\");\nend Hello_World;\n",
    "ops_code": "-- ==========================================\n-- Program: Basic Operations in Ada (+, -, *, /, mod)\n-- ==========================================\nwith Ada.Text_IO; use Ada.Text_IO;\nwith Ada.Integer_Text_IO; use Ada.Integer_Text_IO;\n\nprocedure Basic_Operations is\n    A : Integer := 20;\n    B : Integer := 6;\nbegin\n    Put_Line (\"a = 20, b = 6\");\n    Put (\"Addition (a + b)        : \"); Put (A + B); New_Line;\n    Put (\"Subtraction (a - b)     : \"); Put (A - B); New_Line;\n    Put (\"Multiplication (a * b)  : \"); Put (A * B); New_Line;\n    Put (\"Integer Division (a / b): \"); Put (A / B); New_Line;\n    Put (\"Modulo (a mod b)        : \"); Put (A mod B); New_Line;\nend Basic_Operations;\n"
  },
  {
    "id": "23-haskell",
    "name": "Haskell",
    "ext": "hs",
    "category": "Functional & Declarative",
    "compiler": "ghc-9.8.2",
    "year": "1990",
    "creator": "Simon Peyton Jones et al.",
    "paradigm": "Purely functional, lazy evaluation",
    "install": "GHC / ghcup",
    "run_cmd": "runhaskell hello_world.hs",
    "hw_code": "-- ==========================================\n-- Program: Hello World in Haskell\n-- ==========================================\nmain :: IO ()\nmain = putStrLn \"Hello, World!\"\n",
    "ops_code": "-- ==========================================\n-- Program: Basic Operations in Haskell (+, -, *, div, mod, /)\n-- ==========================================\nmain :: IO ()\nmain = do\n    let a = 20 :: Int\n    let b = 6 :: Int\n    putStrLn \"a = 20, b = 6\"\n    putStrLn (\"Addition (a + b)        : \" ++ show (a + b))\n    putStrLn (\"Subtraction (a - b)     : \" ++ show (a - b))\n    putStrLn (\"Multiplication (a * b)  : \" ++ show (a * b))\n    putStrLn (\"Integer Division (div)  : \" ++ show (a `div` b))\n    putStrLn (\"Float Division (/)      : \" ++ show (fromIntegral a / fromIntegral b))\n    putStrLn (\"Modulo (mod)            : \" ++ show (a `mod` b))\n"
  },
  {
    "id": "24-scala",
    "name": "Scala",
    "ext": "scala",
    "category": "Functional & Declarative",
    "compiler": "scala-3.4.2",
    "year": "2004",
    "creator": "Martin Odersky",
    "paradigm": "Functional, Object-oriented",
    "install": "scala-lang.org",
    "run_cmd": "scala hello_world.scala",
    "hw_code": "// ==========================================\n// Program: Hello World in Scala (Scala 3)\n// ==========================================\n@main def run(): Unit =\n  println(\"Hello, World!\")\n",
    "ops_code": "// ==========================================\n// Program: Basic Operations in Scala (Scala 3)\n// ==========================================\n@main def runOps(): Unit =\n  val a = 20\n  val b = 6\n\n  println(s\"a = $a, b = $b\")\n  println(s\"Addition (a + b)        : ${a + b}\")\n  println(s\"Subtraction (a - b)     : ${a - b}\")\n  println(s\"Multiplication (a * b)  : ${a * b}\")\n  println(s\"Integer Division (a / b): ${a / b}\")\n  println(s\"Float Division (toDouble): ${a.toDouble / b}\")\n  println(s\"Modulo (a % b)          : ${a % b}\")\n"
  },
  {
    "id": "25-clojure",
    "name": "Clojure",
    "ext": "clj",
    "category": "Functional & Declarative",
    "compiler": "clojure-1.11.3",
    "year": "2007",
    "creator": "Rich Hickey",
    "paradigm": "Functional Lisp dialect (JVM hosted)",
    "install": "clojure.org",
    "run_cmd": "clj -M hello_world.clj",
    "hw_code": ";;; ==========================================\n;;; Program: Hello World in Clojure\n;;; ==========================================\n(println \"Hello, World!\")\n",
    "ops_code": ";;; ==========================================\n;;; Program: Basic Operations in Clojure (+, -, *, quot, mod)\n;;; ==========================================\n(let [a 20\n      b 6]\n  (println (str \"a = \" a \", b = \" b))\n  (println (str \"Addition (+ a b)        : \" (+ a b)))\n  (println (str \"Subtraction (- a b)     : \" (- a b)))\n  (println (str \"Multiplication (* a b)  : \" (* a b)))\n  (println (str \"Quotient (quot a b)     : \" (quot a b)))\n  (println (str \"Exact Division (/ a b)  : \" (/ a b)))\n  (println (str \"Modulo (mod a b)        : \" (mod a b))))\n"
  },
  {
    "id": "26-elixir",
    "name": "Elixir",
    "ext": "exs",
    "category": "Functional & Declarative",
    "compiler": "elixir-1.17.1",
    "year": "2012",
    "creator": "José Valim",
    "paradigm": "Functional, Concurrent (Actor model)",
    "install": "elixir-lang.org",
    "run_cmd": "elixir hello_world.exs",
    "hw_code": "# ==========================================\n# Program: Hello World in Elixir\n# ==========================================\nIO.puts(\"Hello, World!\")\n",
    "ops_code": "# ==========================================\n# Program: Basic Operations in Elixir (+, -, *, /, div, rem)\n# ==========================================\na = 20\nb = 6\n\nIO.puts(\"a = #{a}, b = #{b}\")\nIO.puts(\"Addition (a + b)        : #{a + b}\")\nIO.puts(\"Subtraction (a - b)     : #{a - b}\")\nIO.puts(\"Multiplication (a * b)  : #{a * b}\")\nIO.puts(\"Float Division (a / b)  : #{a / b}\")\nIO.puts(\"Integer Division (div)  : #{div(a, b)}\")\nIO.puts(\"Remainder (rem)         : #{rem(a, b)}\")\n"
  },
  {
    "id": "27-erlang",
    "name": "Erlang",
    "ext": "erl",
    "category": "Functional & Declarative",
    "compiler": "erlang-27.0",
    "year": "1986",
    "creator": "Joe Armstrong et al.",
    "paradigm": "Functional, Concurrent (Actor model)",
    "install": "erlang.org",
    "run_cmd": "erlc hello_world.erl && erl -noshell -s hello_world start -s init stop",
    "hw_code": "% ==========================================\n% Program: Hello World in Erlang\n% ==========================================\n-module(hello_world).\n-export([start/0]).\n\nstart() ->\n    io:format(\"Hello, World!~n\").\n",
    "ops_code": "% ==========================================\n% Program: Basic Operations in Erlang (+, -, *, div, rem)\n% ==========================================\n-module(basic_operations).\n-export([start/0]).\n\nstart() ->\n    A = 20,\n    B = 6,\n    io:format(\"a = ~p, b = ~p~n\", [A, B]),\n    io:format(\"Addition: ~p, Subtraction: ~p, Multiplication: ~p, Division: ~p, Remainder: ~p~n\",\n              [A + B, A - B, A * B, A div B, A rem B]).\n"
  },
  {
    "id": "28-ocaml",
    "name": "OCaml",
    "ext": "ml",
    "category": "Functional & Declarative",
    "compiler": "ocaml-5.2.0",
    "year": "1996",
    "creator": "INRIA",
    "paradigm": "Multi-paradigm (Functional, imperative, OOP)",
    "install": "ocaml.org / opam",
    "run_cmd": "ocaml hello_world.ml",
    "hw_code": "(* ==========================================\n   Program: Hello World in OCaml\n   ========================================== *)\nlet () = print_endline \"Hello, World!\"\n",
    "ops_code": "(* ==========================================\n   Program: Basic Operations in OCaml (+, -, *, /, mod)\n   ========================================== *)\nlet () =\n  let a = 20 in\n  let b = 6 in\n  Printf.printf \"a = %d, b = %d\\n\" a b;\n  Printf.printf \"Addition (a + b)        : %d\\n\" (a + b);\n  Printf.printf \"Subtraction (a - b)     : %d\\n\" (a - b);\n  Printf.printf \"Multiplication (a * b)  : %d\\n\" (a * b);\n  Printf.printf \"Integer Division (a / b): %d\\n\" (a / b);\n  Printf.printf \"Float Division (float)  : %f\\n\" (float_of_int a /. float_of_int b);\n  Printf.printf \"Modulo (a mod b)        : %d\\n\" (a mod b)\n"
  },
  {
    "id": "29-fsharp",
    "name": "F#",
    "ext": "fs",
    "category": "Functional & Declarative",
    "compiler": "dotnetcore-8.0.301",
    "year": "2005",
    "creator": "Don Syme (Microsoft Research)",
    "paradigm": "Functional-first, object-oriented, imperative",
    "install": ".NET SDK",
    "run_cmd": "dotnet fsi hello_world.fs",
    "hw_code": "// ==========================================\n// Program: Hello World in F#\n// ==========================================\nprintfn \"Hello, World!\"\n",
    "ops_code": "// ==========================================\n// Program: Basic Operations in F# (+, -, *, /, %)\n// ==========================================\nlet a = 20\nlet b = 6\n\nprintfn \"a = %d, b = %d\" a b\nprintfn \"Addition (a + b)        : %d\" (a + b)\nprintfn \"Subtraction (a - b)     : %d\" (a - b)\nprintfn \"Multiplication (a * b)  : %d\" (a * b)\nprintfn \"Integer Division (a / b): %d\" (a / b)\nprintfn \"Float Division (float)  : %f\" (float a / float b)\nprintfn \"Modulo (a % b)          : %d\" (a % b)\n"
  },
  {
    "id": "30-common-lisp",
    "name": "Common Lisp",
    "ext": "lisp",
    "category": "Functional & Declarative",
    "compiler": "sbcl-2.4.6",
    "year": "1984",
    "creator": "Guy L. Steele Jr. et al.",
    "paradigm": "Multi-paradigm (Symbolic, functional, procedural, OOP)",
    "install": "SBCL",
    "run_cmd": "sbcl --script hello_world.lisp",
    "hw_code": ";;; ==========================================\n;;; Program: Hello World in Common Lisp\n;;; ==========================================\n(format t \"Hello, World!~%\")\n",
    "ops_code": ";;; ==========================================\n;;; Program: Basic Operations in Common Lisp (+, -, *, /, mod)\n;;; ==========================================\n(let ((a 20)\n      (b 6))\n  (format t \"a = ~A, b = ~A~%\" a b)\n  (format t \"Addition (+ a b)        : ~A~%\" (+ a b))\n  (format t \"Subtraction (- a b)     : ~A~%\" (- a b))\n  (format t \"Multiplication (* a b)  : ~A~%\" (* a b))\n  (format t \"Floor Quotient          : ~A~%\" (floor a b))\n  (format t \"Exact Division (/ a b)  : ~A~%\" (/ a b))\n  (format t \"Modulo (mod a b)        : ~A~%\" (mod a b)))\n"
  },
  {
    "id": "31-scheme",
    "name": "Scheme / Racket",
    "ext": "rkt",
    "category": "Functional & Declarative",
    "compiler": "racket-8.12",
    "year": "1975",
    "creator": "Guy L. Steele & Gerald Jay Sussman",
    "paradigm": "Functional (Lisp dialect)",
    "install": "racket-lang.org",
    "run_cmd": "racket hello_world.rkt",
    "hw_code": "#lang racket\n;; ==========================================\n;; Program: Hello World in Racket / Scheme\n;; ==========================================\n(displayln \"Hello, World!\")\n",
    "ops_code": "#lang racket\n;; ==========================================\n;; Program: Basic Operations in Racket / Scheme\n;; ==========================================\n(define a 20)\n(define b 6)\n\n(printf \"a = ~a, b = ~a\\n\" a b)\n(printf \"Addition: ~a, Subtraction: ~a, Multiplication: ~a, Quotient: ~a, Exact Division: ~a, Remainder: ~a\\n\"\n        (+ a b)\n        (- a b)\n        (* a b)\n        (quotient a b)\n        (/ a b)\n        (remainder a b))\n"
  },
  {
    "id": "32-bash",
    "name": "Bash",
    "ext": "sh",
    "category": "Shell & Scripting",
    "compiler": "bash",
    "year": "1989",
    "creator": "Brian Fox",
    "paradigm": "Command Language, Scripting",
    "install": "Built-in / Git Bash",
    "run_cmd": "bash hello_world.sh",
    "hw_code": "#!/usr/bin/env bash\n# ==========================================\n# Program: Hello World in Bash\n# ==========================================\necho \"Hello, World!\"\n",
    "ops_code": "#!/usr/bin/env bash\n# ==========================================\n# Program: Basic Operations in Bash (+, -, *, /, %)\n# ==========================================\na=20\nb=6\n\necho \"a = $a, b = $b\"\necho \"Addition (a + b)        : $((a + b))\"\necho \"Subtraction (a - b)     : $((a - b))\"\necho \"Multiplication (a * b)  : $((a * b))\"\necho \"Integer Division (a / b): $((a / b))\"\necho \"Modulo (a % b)          : $((a % b))\"\n"
  },
  {
    "id": "33-powershell",
    "name": "PowerShell",
    "ext": "ps1",
    "category": "Shell & Scripting",
    "compiler": "powershell",
    "year": "2006",
    "creator": "Jeffrey Snover (Microsoft)",
    "paradigm": "Task-based command-line shell & scripting language",
    "install": "Built-in Windows / pwsh",
    "run_cmd": "powershell -ExecutionPolicy Bypass -File hello_world.ps1",
    "hw_code": "# ==========================================\n# Program: Hello World in PowerShell\n# ==========================================\nWrite-Output \"Hello, World!\"\n",
    "ops_code": "# ==========================================\n# Program: Basic Operations in PowerShell (+, -, *, /, %)\n# ==========================================\n$a = 20\n$b = 6\n\nWrite-Output \"a = $a, b = $b\"\nWrite-Output \"Addition (a + b)        : $($a + $b)\"\nWrite-Output \"Subtraction (a - b)     : $($a - $b)\"\nWrite-Output \"Multiplication (a * b)  : $($a * $b)\"\nWrite-Output \"Division (a / b)        : $($a / $b)\"\nWrite-Output \"Integer Division ([int]): $([Math]::Floor($a / $b))\"\nWrite-Output \"Modulo (a % b)          : $($a % $b)\"\n"
  },
  {
    "id": "34-batch",
    "name": "Windows Batch",
    "ext": "bat",
    "category": "Shell & Scripting",
    "compiler": "cmd",
    "year": "1981",
    "creator": "Microsoft",
    "paradigm": "Command script",
    "install": "Built-in Windows",
    "run_cmd": "hello_world.bat",
    "hw_code": "@echo off\nrem ==========================================\nrem Program: Hello World in Windows Batch\nrem ==========================================\necho Hello, World!\n",
    "ops_code": "@echo off\nrem ==========================================\nrem Program: Basic Operations in Windows Batch (+, -, *, /, %%)\nrem ==========================================\nset a=20\nset b=6\n\nset /a add=a+b\nset /a sub=a-b\nset /a mul=a*b\nset /a div=a/b\nset /a mod=a%%b\n\necho a = %a%, b = %b%\necho Addition (a + b)        : %add%\necho Subtraction (a - b)     : %sub%\necho Multiplication (a * b)  : %mul%\necho Integer Division (a / b): %div%\necho Modulo (a %%%% b)          : %mod%\n"
  },
  {
    "id": "35-lua",
    "name": "Lua",
    "ext": "lua",
    "category": "Shell & Scripting",
    "compiler": "lua-5.4.6",
    "year": "1993",
    "creator": "Roberto Ierusalimschy et al.",
    "paradigm": "Multi-paradigm (Scripting, procedural, prototype-based)",
    "install": "lua.org",
    "run_cmd": "lua hello_world.lua",
    "hw_code": "-- ==========================================\n-- Program: Hello World in Lua\n-- ==========================================\nprint(\"Hello, World!\")\n",
    "ops_code": "-- ==========================================\n-- Program: Basic Operations in Lua (+, -, *, /, //, %)\n-- ==========================================\nlocal a = 20\nlocal b = 6\n\nprint(string.format(\"a = %d, b = %d\", a, b))\nprint(string.format(\"Addition (a + b)        : %d\", a + b))\nprint(string.format(\"Subtraction (a - b)     : %d\", a - b))\nprint(string.format(\"Multiplication (a * b)  : %d\", a * b))\nprint(string.format(\"Division (a / b)        : %f\", a / b))\nprint(string.format(\"Integer Division (a // b): %d\", a // b)) -- Lua 5.3+ integer division\nprint(string.format(\"Modulo (a %%%% b)          : %d\", a % b))\n"
  },
  {
    "id": "36-perl",
    "name": "Perl",
    "ext": "pl",
    "category": "Shell & Scripting",
    "compiler": "perl-5.38.2",
    "year": "1987",
    "creator": "Larry Wall",
    "paradigm": "Multi-paradigm (Procedural, functional, OOP)",
    "install": "perl.org",
    "run_cmd": "perl hello_world.pl",
    "hw_code": "#!/usr/bin/env perl\n# ==========================================\n# Program: Hello World in Perl\n# ==========================================\nuse strict;\nuse warnings;\n\nprint \"Hello, World!\n\";\n",
    "ops_code": "#!/usr/bin/env perl\n# ==========================================\n# Program: Basic Operations in Perl (+, -, *, /, %)\n# ==========================================\nuse strict;\nuse warnings;\n\nmy $a = 20;\nmy $b = 6;\n\nprint \"a = $a, b = $b\n\";\nprint \"Addition (a + b)        : \" . ($a + $b) . \"\n\";\nprint \"Subtraction (a - b)     : \" . ($a - $b) . \"\n\";\nprint \"Multiplication (a * b)  : \" . ($a * $b) . \"\n\";\nprint \"Division (a / b)        : \" . ($a / $b) . \"\n\";\nprint \"Integer Division (int)  : \" . int($a / $b) . \"\n\";\nprint \"Modulo (a % b)          : \" . ($a % $b) . \"\n\";\n"
  },
  {
    "id": "37-awk",
    "name": "AWK",
    "ext": "awk",
    "category": "Shell & Scripting",
    "compiler": "gawk-5.3.0",
    "year": "1977",
    "creator": "Alfred Aho et al.",
    "paradigm": "Data-driven, pattern scanning and processing",
    "install": "gawk",
    "run_cmd": "awk -f hello_world.awk /dev/null",
    "hw_code": "# ==========================================\n# Program: Hello World in AWK\n# ==========================================\nBEGIN {\n    print \"Hello, World!\"\n}\n",
    "ops_code": "# ==========================================\n# Program: Basic Operations in AWK (+, -, *, /, %)\n# ==========================================\nBEGIN {\n    a = 20\n    b = 6\n\n    printf \"a = %d, b = %d\\n\", a, b\n    printf \"Addition (a + b)        : %d\\n\", a + b\n    printf \"Subtraction (a - b)     : %d\\n\", a - b\n    printf \"Multiplication (a * b)  : %d\\n\", a * b\n    printf \"Division (a / b)        : %f\\n\", a / b\n    printf \"Integer Division (int)  : %d\\n\", int(a / b)\n    printf \"Modulo (a %%%% b)          : %d\\n\", a % b\n}\n"
  },
  {
    "id": "38-tcl",
    "name": "Tcl",
    "ext": "tcl",
    "category": "Shell & Scripting",
    "compiler": "tcl-8.6.14",
    "year": "1988",
    "creator": "John Ousterhout",
    "paradigm": "Command-driven, functional, imperative",
    "install": "tcl.tk",
    "run_cmd": "tclsh hello_world.tcl",
    "hw_code": "# ==========================================\n# Program: Hello World in Tcl\n# ==========================================\nputs \"Hello, World!\"\n",
    "ops_code": "# ==========================================\n# Program: Basic Operations in Tcl (+, -, *, /, %)\n# ==========================================\nset a 20\nset b 6\n\nputs \"a = $a, b = $b\"\nputs \"Addition (a + b)        : [expr {$a + $b}]\"\nputs \"Subtraction (a - b)     : [expr {$a - $b}]\"\nputs \"Multiplication (a * b)  : [expr {$a * $b}]\"\nputs \"Integer Division (a / b): [expr {$a / $b}]\"\nputs \"Float Division          : [expr {double($a) / $b}]\"\nputs \"Modulo (a % b)          : [expr {$a % $b}]\"\n"
  },
  {
    "id": "39-dart",
    "name": "Dart",
    "ext": "dart",
    "category": "Web3, Mobile & Modern",
    "compiler": "dart-3.4.3",
    "year": "2011",
    "creator": "Lars Bak and Kasper Lund (Google)",
    "paradigm": "Multi-paradigm (Object-oriented, class-based)",
    "install": "dart.dev",
    "run_cmd": "dart run hello_world.dart",
    "hw_code": "// ==========================================\n// Program: Hello World in Dart\n// ==========================================\nvoid main() {\n  print('Hello, World!');\n}\n",
    "ops_code": "// ==========================================\n// Program: Basic Operations in Dart (+, -, *, /, ~/, %)\n// ==========================================\nvoid main() {\n  int a = 20;\n  int b = 6;\n\n  print('a = $a, b = $b');\n  print('Addition (a + b)        : ${a + b}');\n  print('Subtraction (a - b)     : ${a - b}');\n  print('Multiplication (a * b)  : ${a * b}');\n  print('Division (a / b)        : ${a / b}');\n  print('Integer Division (~/)   : ${a ~/ b}'); // ~/ is truncating integer division in Dart\n  print('Modulo (a % b)          : ${a % b}');\n}\n"
  },
  {
    "id": "40-objective-c",
    "name": "Objective-C",
    "ext": "m",
    "category": "Web3, Mobile & Modern",
    "compiler": "clang-18.1.0",
    "year": "1984",
    "creator": "Brad Cox and Tom Love",
    "paradigm": "Object-oriented, reflective",
    "install": "Clang / GNUstep / Xcode",
    "run_cmd": "clang -framework Foundation hello_world.m -o hello_world && ./hello_world",
    "hw_code": "// ==========================================\n// Program: Hello World in Objective-C\n// ==========================================\n#import <Foundation/Foundation.h>\n\nint main(int argc, const char * argv[]) {\n    @autoreleasepool {\n        NSLog(@\"Hello, World!\");\n    }\n    return 0;\n}\n",
    "ops_code": "// ==========================================\n// Program: Basic Operations in Objective-C (+, -, *, /, %)\n// ==========================================\n#import <Foundation/Foundation.h>\n\nint main(int argc, const char * argv[]) {\n    @autoreleasepool {\n        int a = 20;\n        int b = 6;\n\n        NSLog(@\"a = %d, b = %d\", a, b);\n        NSLog(@\"Addition (a + b)        : %d\", a + b);\n        NSLog(@\"Subtraction (a - b)     : %d\", a - b);\n        NSLog(@\"Multiplication (a * b)  : %d\", a * b);\n        NSLog(@\"Integer Division (a / b): %d\", a / b);\n        NSLog(@\"Float Division (double) : %f\", (double)a / b);\n        NSLog(@\"Modulo (a %% b)          : %d\", a % b);\n    }\n    return 0;\n}\n"
  },
  {
    "id": "41-v",
    "name": "V (Vlang)",
    "ext": "v",
    "category": "Web3, Mobile & Modern",
    "compiler": "v-0.4.6",
    "year": "2019",
    "creator": "Alexander Medvednikov",
    "paradigm": "Static, procedural, safe systems language",
    "install": "vlang.io",
    "run_cmd": "v run hello_world.v",
    "hw_code": "// ==========================================\n// Program: Hello World in V (Vlang)\n// ==========================================\nfn main() {\n    println('Hello, World!')\n}\n",
    "ops_code": "// ==========================================\n// Program: Basic Operations in V (+, -, *, /, %)\n// ==========================================\nfn main() {\n    a := 20\n    b := 6\n\n    println('a = $a, b = $b')\n    println('Addition (a + b)        : ${a + b}')\n    println('Subtraction (a - b)     : ${a - b}')\n    println('Multiplication (a * b)  : ${a * b}')\n    println('Integer Division (a / b): ${a / b}')\n    println('Float Division (f64)    : ${f64(a) / f64(b)}')\n    println('Modulo (a % b)          : ${a % b}')\n}\n"
  },
  {
    "id": "42-crystal",
    "name": "Crystal",
    "ext": "cr",
    "category": "Web3, Mobile & Modern",
    "compiler": "crystal-1.12.2",
    "year": "2014",
    "creator": "Ary Borenszweig et al.",
    "paradigm": "Object-oriented, compiled, statically type-checked",
    "install": "crystal-lang.org",
    "run_cmd": "crystal run hello_world.cr",
    "hw_code": "# ==========================================\n# Program: Hello World in Crystal\n# ==========================================\nputs \"Hello, World!\"\n",
    "ops_code": "# ==========================================\n# Program: Basic Operations in Crystal (+, -, *, /, //, %)\n# ==========================================\na = 20\nb = 6\n\nputs \"a = #{a}, b = #{b}\"\nputs \"Addition (a + b)        : #{a + b}\"\nputs \"Subtraction (a - b)     : #{a - b}\"\nputs \"Multiplication (a * b)  : #{a * b}\"\nputs \"Float Division (a / b)  : #{a / b}\"\nputs \"Integer Division (//)   : #{a // b}\" # // is integer division in Crystal\nputs \"Modulo (a % b)          : #{a % b}\"\n"
  },
  {
    "id": "43-solidity",
    "name": "Solidity",
    "ext": "sol",
    "category": "Web3, Mobile & Modern",
    "compiler": "solc-0.8.26",
    "year": "2014",
    "creator": "Gavin Wood et al.",
    "paradigm": "Contract-oriented, static typing (Ethereum EVM)",
    "install": "`npm install -g solc`",
    "run_cmd": "solc --bin hello_world.sol",
    "hw_code": "// SPDX-License-Identifier: MIT\npragma solidity ^0.8.20;\n\n// ==========================================\n// Program: Hello World in Solidity (Ethereum Smart Contract)\n// ==========================================\ncontract HelloWorld {\n    string public greeting = \"Hello, World!\";\n\n    function getGreeting() public view returns (string memory) {\n        return greeting;\n    }\n}\n",
    "ops_code": "// SPDX-License-Identifier: MIT\npragma solidity ^0.8.20;\n\n// ==========================================\n// Program: Basic Operations in Solidity (+, -, *, /, %)\n// ==========================================\ncontract BasicOperations {\n    // Calculates +, -, *, /, % on the Ethereum Virtual Machine\n    function calculate(uint256 a, uint256 b) public pure returns (\n        uint256 addResult,\n        uint256 subResult,\n        uint256 mulResult,\n        uint256 divResult,\n        uint256 modResult\n    ) {\n        addResult = a + b;\n        subResult = a - b;\n        mulResult = a * b;\n        divResult = a / b; // EVM integer division truncates\n        modResult = a % b; // Modulo remainder\n    }\n}\n"
  },
  {
    "id": "44-sql",
    "name": "SQL",
    "ext": "sql",
    "category": "Web3, Mobile & Modern",
    "compiler": "sqlite-3.46.0",
    "year": "1974",
    "creator": "Donald D. Chamberlin and Raymond F. Boyce (IBM)",
    "paradigm": "Declarative (Relational Database Query Language)",
    "install": "SQLite / PostgreSQL / MySQL",
    "run_cmd": "sqlite3 :memory: < hello_world.sql",
    "hw_code": "-- ==========================================\n-- Program: Hello World in SQL (ANSI Standard)\n-- ==========================================\nSELECT 'Hello, World!' AS message;\n",
    "ops_code": "-- ==========================================\n-- Program: Basic Operations in SQL (+, -, *, /, %)\n-- ==========================================\nSELECT\n    20 + 6 AS addition,\n    20 - 6 AS subtraction,\n    20 * 6 AS multiplication,\n    20 / 6 AS integer_division,\n    20 * 1.0 / 6 AS float_division,\n    20 % 6 AS modulo;\n"
  },
  {
    "id": "45-cobol",
    "name": "COBOL",
    "ext": "cob",
    "category": "Classic & Foundational",
    "compiler": "gnucobol-3.2",
    "year": "1959",
    "creator": "CODASYL (Grace Hopper influence)",
    "paradigm": "Imperative, procedural (Business computing)",
    "install": "GnuCOBOL",
    "run_cmd": "cobc -x hello_world.cob -o hello_world && ./hello_world",
    "hw_code": "      * ==========================================\n      * Program: Hello World in COBOL\n      * ==========================================\n       IDENTIFICATION DIVISION.\n       PROGRAM-ID. HELLO-WORLD.\n\n       PROCEDURE DIVISION.\n           DISPLAY 'Hello, World!'.\n           STOP RUN.\n",
    "ops_code": "      * ==========================================\n      * Program: Basic Operations in COBOL (+, -, *, /, %)\n      * ==========================================\n       IDENTIFICATION DIVISION.\n       PROGRAM-ID. BASIC-OPS.\n\n       DATA DIVISION.\n       WORKING-STORAGE SECTION.\n       01 A          PIC 99 VALUE 20.\n       01 B          PIC 99 VALUE 6.\n       01 RES-ADD    PIC 99.\n       01 RES-SUB    PIC 99.\n       01 RES-MUL    PIC 999.\n       01 RES-DIV    PIC 99.\n       01 RES-MOD    PIC 99.\n\n       PROCEDURE DIVISION.\n           COMPUTE RES-ADD = A + B.\n           COMPUTE RES-SUB = A - B.\n           COMPUTE RES-MUL = A * B.\n           DIVIDE A BY B GIVING RES-DIV REMAINDER RES-MOD.\n\n           DISPLAY 'A = 20, B = 6'.\n           DISPLAY 'ADDITION: ' RES-ADD.\n           DISPLAY 'SUBTRACTION: ' RES-SUB.\n           DISPLAY 'MULTIPLICATION: ' RES-MUL.\n           DISPLAY 'DIVISION: ' RES-DIV.\n           DISPLAY 'REMAINDER: ' RES-MOD.\n           STOP RUN.\n"
  },
  {
    "id": "46-pascal",
    "name": "Pascal",
    "ext": "pas",
    "category": "Classic & Foundational",
    "compiler": "fpc-3.2.2",
    "year": "1970",
    "creator": "Niklaus Wirth",
    "paradigm": "Imperative, structured, procedural",
    "install": "Free Pascal Compiler (FPC)",
    "run_cmd": "fpc hello_world.pas && ./hello_world",
    "hw_code": "(* ==========================================\n   Program: Hello World in Pascal\n   ========================================== *)\nprogram HelloWorld;\nbegin\n    writeln('Hello, World!');\nend.\n",
    "ops_code": "(* ==========================================\n   Program: Basic Operations in Pascal (+, -, *, /, div, mod)\n   ========================================== *)\nprogram BasicOperations;\nvar\n    a, b: integer;\nbegin\n    a := 20;\n    b := 6;\n\n    writeln('a = 20, b = 6');\n    writeln('Addition (a + b)        : ', a + b);\n    writeln('Subtraction (a - b)     : ', a - b);\n    writeln('Multiplication (a * b)  : ', a * b);\n    writeln('Integer Division (div)  : ', a div b);\n    writeln('Float Division (/)      : ', (a / b):0:2);\n    writeln('Modulo (mod)            : ', a mod b);\nend.\n"
  },
  {
    "id": "47-basic",
    "name": "BASIC",
    "ext": "bas",
    "category": "Classic & Foundational",
    "compiler": "freebasic-1.10.1",
    "year": "1964",
    "creator": "John G. Kemeny & Thomas E. Kurtz",
    "paradigm": "Imperative, procedural",
    "install": "FreeBASIC",
    "run_cmd": "fbc -lang qb hello_world.bas && ./hello_world",
    "hw_code": "10 REM ==========================================\n20 REM Program: Hello World in Classic BASIC\n30 REM ==========================================\n40 PRINT \"Hello, World!\"\n50 END\n",
    "ops_code": "10 REM ==========================================\n20 REM Program: Basic Operations in Classic BASIC (+, -, *, \\, MOD)\n30 REM ==========================================\n40 A = 20\n50 B = 6\n60 PRINT \"a = 20, b = 6\"\n70 PRINT \"Addition: \"; A + B; \", Subtraction: \"; A - B; \", Multiplication: \"; A * B; \", Division: \"; A \\ B; \", Modulo: \"; A MOD B\n80 END\n"
  },
  {
    "id": "48-forth",
    "name": "Forth",
    "ext": "fs",
    "category": "Classic & Foundational",
    "compiler": "gforth-0.7.3",
    "year": "1970",
    "creator": "Charles H. Moore",
    "paradigm": "Stack-oriented, concatenative, procedural",
    "install": "Gforth",
    "run_cmd": "gforth hello_world.fs -e bye",
    "hw_code": "\\ ==========================================\n\\ Program: Hello World in Forth\n\\ ==========================================\n: HELLO ( -- )\n  .\" Hello, World!\" CR ;\n\nHELLO\n",
    "ops_code": "\\ ==========================================\n\\ Program: Basic Operations in Forth (+, -, *, /, MOD)\n\\ ==========================================\n: OPERATIONS ( -- )\n  .\" a = 20, b = 6\" CR\n  .\" Addition: \" 20 6 + . CR\n  .\" Subtraction: \" 20 6 - . CR\n  .\" Multiplication: \" 20 6 * . CR\n  .\" Division: \" 20 6 / . CR\n  .\" Modulo: \" 20 6 MOD . CR ;\n\nOPERATIONS\n"
  },
  {
    "id": "49-smalltalk",
    "name": "Smalltalk",
    "ext": "st",
    "category": "Classic & Foundational",
    "compiler": "gnu-smalltalk-3.2.5",
    "year": "1972",
    "creator": "Alan Kay et al. (Xerox PARC)",
    "paradigm": "Pure object-oriented, message passing",
    "install": "GNU Smalltalk (gst)",
    "run_cmd": "gst hello_world.st",
    "hw_code": "\"==========================================\n Program: Hello World in Smalltalk\n ==========================================\"\nTranscript show: 'Hello, World!'; cr.\n",
    "ops_code": "\"==========================================\n Program: Basic Operations in Smalltalk (+, -, *, //, \\\\)\n ==========================================\"\n| a b |\na := 20.\nb := 6.\n\nTranscript show: 'a = 20, b = 6'; cr.\nTranscript show: 'Addition (a + b)        : ', (a + b) printString; cr.\nTranscript show: 'Subtraction (a - b)     : ', (a - b) printString; cr.\nTranscript show: 'Multiplication (a * b)  : ', (a * b) printString; cr.\nTranscript show: 'Integer Division (//)   : ', (a // b) printString; cr.\nTranscript show: 'Exact Fraction (/)      : ', (a / b) printString; cr.\nTranscript show: 'Modulo (\\\\)             : ', (a \\\\ b) printString; cr.\n"
  },
  {
    "id": "50-prolog",
    "name": "Prolog",
    "ext": "pl",
    "category": "Classic & Foundational",
    "compiler": "swi-prolog-9.2.4",
    "year": "1972",
    "creator": "Alain Colmerauer and Philippe Roussel",
    "paradigm": "Declarative, Logic programming",
    "install": "SWI-Prolog",
    "run_cmd": "swipl -q -t main -f hello_world.pl",
    "hw_code": "% ==========================================\n% Program: Hello World in Prolog (SWI-Prolog)\n% ==========================================\n:- initialization(main).\n\nmain :-\n    write('Hello, World!'), nl,\n    halt.\n",
    "ops_code": "% ==========================================\n% Program: Basic Operations in Prolog (+, -, *, //, mod)\n% ==========================================\n:- initialization(main).\n\nmain :-\n    A = 20,\n    B = 6,\n    Add is A + B,\n    Sub is A - B,\n    Mul is A * B,\n    Div is A // B,   % // is integer division in ISO Prolog\n    Mod is A mod B,  % mod is modulo remainder\n    format('a = ~w, b = ~w~n', [A, B]),\n    format('Addition: ~w, Subtraction: ~w, Multiplication: ~w, Division: ~w, Modulo: ~w~n',\n           [Add, Sub, Mul, Div, Mod]),\n    halt.\n"
  }
];
